name: pickaboo_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_fonts: ^4.0.0
  path_provider: ^2.0.15
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.1.0
  expandable: ^5.0.1
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  http: ^0.13.5
  flutter_paystack: ^1.0.7
  flutter_rating_bar: ^4.0.1
  dio: ^5.2.1+1
  cached_network_image: ^3.2.3
  file_picker: ^5.3.2
  animations: ^2.0.7
  flutter_animate: ^4.2.0
  image_picker: ^1.0.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.3.1
  location: ^4.4.0
  intl: ^0.17.0
  badges: ^3.1.1
  flutter_polyline_points: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true

  color: "#ffffff"
  image: assets/images/pickaboo_logo.png
  image_dark: "assets/images/pickaboo_logo.png"

  android12:
    image: "assets/images/pickaboo_logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/pickaboo_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/cards/
