name: pickaboo_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_fonts: ^4.0.0
  path_provider: ^2.0.15
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.1.0
  expandable: ^5.0.1
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  http: ^0.13.5
  flutter_paystack: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  
  background_image: 'assets/images/splash_screen.png'

  android12:
    image: 'assets/images/pickaboo_logo.png'
    icon_background_color: "#ffffff"
    image_dark: 'assets/images/pickaboo_logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/cards/
